/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface TweetStorageInterface extends utils.Interface {
  functions: {
    "changeVoteInTweet(uint256,int256)": FunctionFragment;
    "controllerAddr()": FunctionFragment;
    "createTweet(uint256,string)": FunctionFragment;
    "doesTweetExist(uint256)": FunctionFragment;
    "getNumTweets()": FunctionFragment;
    "getTweetIdsFromUser(uint256)": FunctionFragment;
    "ownerAddr()": FunctionFragment;
    "setControllerAddr(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "tweetIds(uint256)": FunctionFragment;
    "tweetToVotes(uint256)": FunctionFragment;
    "tweets(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "changeVoteInTweet"
      | "controllerAddr"
      | "createTweet"
      | "doesTweetExist"
      | "getNumTweets"
      | "getTweetIdsFromUser"
      | "ownerAddr"
      | "setControllerAddr"
      | "transferOwnership"
      | "tweetIds"
      | "tweetToVotes"
      | "tweets"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "changeVoteInTweet",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "controllerAddr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createTweet",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "doesTweetExist",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNumTweets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTweetIdsFromUser",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "ownerAddr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setControllerAddr",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "tweetIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tweetToVotes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tweets",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "changeVoteInTweet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "controllerAddr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTweet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "doesTweetExist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNumTweets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTweetIdsFromUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ownerAddr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setControllerAddr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tweetIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tweetToVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tweets", data: BytesLike): Result;

  events: {};
}

export interface TweetStorage extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TweetStorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    changeVoteInTweet(
      _tweetId: BigNumberish,
      changeValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    controllerAddr(overrides?: CallOverrides): Promise<[string]>;

    createTweet(
      _userId: BigNumberish,
      _text: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    doesTweetExist(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getNumTweets(overrides?: CallOverrides): Promise<[BigNumber]>;

    getTweetIdsFromUser(
      _userId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    ownerAddr(overrides?: CallOverrides): Promise<[string]>;

    setControllerAddr(
      _controllerAdrr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tweetIds(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    tweetToVotes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    tweets(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, BigNumber] & {
        id: BigNumber;
        text: string;
        userId: BigNumber;
        postedAt: BigNumber;
      }
    >;
  };

  changeVoteInTweet(
    _tweetId: BigNumberish,
    changeValue: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  controllerAddr(overrides?: CallOverrides): Promise<string>;

  createTweet(
    _userId: BigNumberish,
    _text: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  doesTweetExist(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getNumTweets(overrides?: CallOverrides): Promise<BigNumber>;

  getTweetIdsFromUser(
    _userId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  ownerAddr(overrides?: CallOverrides): Promise<string>;

  setControllerAddr(
    _controllerAdrr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    _newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tweetIds(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  tweetToVotes(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  tweets(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, BigNumber, BigNumber] & {
      id: BigNumber;
      text: string;
      userId: BigNumber;
      postedAt: BigNumber;
    }
  >;

  callStatic: {
    changeVoteInTweet(
      _tweetId: BigNumberish,
      changeValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    controllerAddr(overrides?: CallOverrides): Promise<string>;

    createTweet(
      _userId: BigNumberish,
      _text: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    doesTweetExist(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getNumTweets(overrides?: CallOverrides): Promise<BigNumber>;

    getTweetIdsFromUser(
      _userId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    ownerAddr(overrides?: CallOverrides): Promise<string>;

    setControllerAddr(
      _controllerAdrr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      _newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    tweetIds(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    tweetToVotes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tweets(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, BigNumber] & {
        id: BigNumber;
        text: string;
        userId: BigNumber;
        postedAt: BigNumber;
      }
    >;
  };

  filters: {};

  estimateGas: {
    changeVoteInTweet(
      _tweetId: BigNumberish,
      changeValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    controllerAddr(overrides?: CallOverrides): Promise<BigNumber>;

    createTweet(
      _userId: BigNumberish,
      _text: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    doesTweetExist(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNumTweets(overrides?: CallOverrides): Promise<BigNumber>;

    getTweetIdsFromUser(
      _userId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ownerAddr(overrides?: CallOverrides): Promise<BigNumber>;

    setControllerAddr(
      _controllerAdrr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tweetIds(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    tweetToVotes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tweets(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    changeVoteInTweet(
      _tweetId: BigNumberish,
      changeValue: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    controllerAddr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createTweet(
      _userId: BigNumberish,
      _text: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    doesTweetExist(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNumTweets(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTweetIdsFromUser(
      _userId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ownerAddr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setControllerAddr(
      _controllerAdrr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tweetIds(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tweetToVotes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tweets(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
