/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface UserStorageInterface extends utils.Interface {
  functions: {
    "addresses(address)": FunctionFragment;
    "controllerAddr()": FunctionFragment;
    "createUser(address,bytes32,bytes32,bytes32,string,string)": FunctionFragment;
    "ownerAddr()": FunctionFragment;
    "profiles(uint256)": FunctionFragment;
    "setControllerAddr(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "usernames(bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addresses"
      | "controllerAddr"
      | "createUser"
      | "ownerAddr"
      | "profiles"
      | "setControllerAddr"
      | "transferOwnership"
      | "usernames"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "addresses", values: [string]): string;
  encodeFunctionData(
    functionFragment: "controllerAddr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createUser",
    values: [string, BytesLike, BytesLike, BytesLike, string, string]
  ): string;
  encodeFunctionData(functionFragment: "ownerAddr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "profiles",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setControllerAddr",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "usernames",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "addresses", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "controllerAddr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createUser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerAddr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "profiles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setControllerAddr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usernames", data: BytesLike): Result;

  events: {};
}

export interface UserStorage extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: UserStorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addresses(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    controllerAddr(overrides?: CallOverrides): Promise<[string]>;

    createUser(
      _address: string,
      _username: BytesLike,
      _firstName: BytesLike,
      _lastName: BytesLike,
      _bio: string,
      _eMail: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ownerAddr(overrides?: CallOverrides): Promise<[string]>;

    profiles(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, string, string, string] & {
        id: BigNumber;
        username: string;
        firstName: string;
        lastName: string;
        bio: string;
        eMail: string;
      }
    >;

    setControllerAddr(
      _controllerAdrr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    usernames(arg0: BytesLike, overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  addresses(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  controllerAddr(overrides?: CallOverrides): Promise<string>;

  createUser(
    _address: string,
    _username: BytesLike,
    _firstName: BytesLike,
    _lastName: BytesLike,
    _bio: string,
    _eMail: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ownerAddr(overrides?: CallOverrides): Promise<string>;

  profiles(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, string, string, string, string] & {
      id: BigNumber;
      username: string;
      firstName: string;
      lastName: string;
      bio: string;
      eMail: string;
    }
  >;

  setControllerAddr(
    _controllerAdrr: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    _newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  usernames(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    addresses(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    controllerAddr(overrides?: CallOverrides): Promise<string>;

    createUser(
      _address: string,
      _username: BytesLike,
      _firstName: BytesLike,
      _lastName: BytesLike,
      _bio: string,
      _eMail: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ownerAddr(overrides?: CallOverrides): Promise<string>;

    profiles(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, string, string, string] & {
        id: BigNumber;
        username: string;
        firstName: string;
        lastName: string;
        bio: string;
        eMail: string;
      }
    >;

    setControllerAddr(
      _controllerAdrr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      _newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    usernames(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    addresses(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    controllerAddr(overrides?: CallOverrides): Promise<BigNumber>;

    createUser(
      _address: string,
      _username: BytesLike,
      _firstName: BytesLike,
      _lastName: BytesLike,
      _bio: string,
      _eMail: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ownerAddr(overrides?: CallOverrides): Promise<BigNumber>;

    profiles(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    setControllerAddr(
      _controllerAdrr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    usernames(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addresses(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    controllerAddr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createUser(
      _address: string,
      _username: BytesLike,
      _firstName: BytesLike,
      _lastName: BytesLike,
      _bio: string,
      _eMail: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ownerAddr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    profiles(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setControllerAddr(
      _controllerAdrr: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      _newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    usernames(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
