/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  BaseController,
  BaseControllerInterface,
} from "../BaseController";

const _abi = [
  {
    inputs: [],
    name: "ownerAddr",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_managerAddr",
        type: "address",
      },
    ],
    name: "setManagerAddr",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class BaseController__factory {
  static readonly abi = _abi;
  static createInterface(): BaseControllerInterface {
    return new utils.Interface(_abi) as BaseControllerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BaseController {
    return new Contract(address, _abi, signerOrProvider) as BaseController;
  }
}
